### ISSUE TITLE
Theme Studio Not Loading

### ISSUE THREAD

**Issue by ericmutta** [syncfusion/ej2-themestudio#4]
I am trying to access the Theme Studio on the official link here https://ej2.syncfusion.com/themestudio/ using Chrome 94 on Windows 8.1 and it is not loading (the spinner just keeps spinning forever). Same thing happens on Chrome for Android. Are you aware of the issue or is it just my devices?

**Comment by ghost** [comment]
Hi Eric Mutta,

Please try the link in the incognito window after clearing the caches.

Theme studio: https://ej2.syncfusion.com/themestudio/?theme=bootstrap5

Regards,
Gokul

**Comment by ericmutta** [comment]
Hi @GOKUL3897 many thanks for following up. It seems to work now when using the incognito window :+1:
